export type Config = {
  sb: number;
  bb: number;
  timebank: number;
  refill: number;
  straddle: boolean;
  twice: boolean;
};
export type Player = {
  id: string;
  name: string;
  seat: number | null;
  stack: number;
  holding: number;
  buyin: number;
  buyout: number;
  profit: number;
  away: boolean;
  online: boolean;
  offline: number;
  bank: number;
  hands: number;
  leave: boolean;
  banned: boolean;
  bet: number;
  folded: boolean;
  cards: (string | null)[];
};
export type JoinRequest = {
  id: string;
  kind: string;
  pid: string;
  name: string;
  seat: number;
  amount: number;
  approved: boolean;
};
export type Hand = {
  number: number;
  ids: string[];
  seats: number[];
  button: number;
  boards: string[][];
  deal?: { seq: number; start: number; until: number; previous: number[] } | null;
  own_hand_labels?: string[][];
  showdown_results?: PotResult[];
  cards: Record<string, (string | null)[]>;
  revealed: string[];
  shown_cards: Record<string, number[]>;
  reveal_until: number;
  result: { pid: string; name: string; delta: number; won: number }[] | null;
  awards: { amounts: number[]; pot: number; board: number | null }[];
  votes: Record<string, boolean>;
  voters: string[];
  runouts: number | null;
  seq: number;
  clock: {
    pid: string;
    base_until: number;
    until: number;
    initial: number;
  } | null;
  last_actions: Record<string, string>;
};
export type PotResult = {
  board: number;
  pot: number;
  winners: { pid: string; amount: number; label: string; cards: string[] }[];
};
export type Ledger = {
  id: string;
  pid: string;
  name: string;
  kind: string;
  amount: number;
  at: number;
  by: string;
  reverses: string | null;
};
export type Room = {
  id: string;
  name: string;
  settings: Config;
  owner: string;
  phase: string;
  deadline: number | null;
  button: number | null;
  small_blind: number | null;
  big_blind: number | null;
  number: number;
  started: boolean;
  paused: boolean;
  recovery: boolean;
  closing: boolean;
  closed_at: number | null;
  version: number;
  me: string;
  players: Player[];
  hand: Hand | null;
  server_time: number;
  requests: JoinRequest[];
  logs: { id: number; at: number; hand: number; kind: string; text: string }[];
  ledger: Ledger[];
  history: Hand[];
  rebuy: string[];
  straddle: string | null;
  pot: number;
  pots: number[];
  recovery_code: string;
  legal: {
    fold: boolean;
    call: number;
    can_call: boolean;
    can_raise: boolean;
    min_raise: number | null;
    max_raise: number | null;
  } | null;
};
