export type Config = {
  short_deck?: boolean;
  sb: number;
  bb: number;
  timebank: number;
  refill: number;
  straddle: boolean;
  twice: boolean;
  bounty: boolean;
  bounty_amount: number | null;
  squid: boolean;
  squid_amount: number | null;
  squid_reveal: boolean;
};
export type BountyRule = { enabled: boolean; amount: number | null };
export type BountyAward = {
  id: string; pid: string; name: string; amount: number; total: number; at: number;
  payments: { pid: string; name: string; amount: number }[];
};
export type SquidRule = { enabled: boolean; amount: number | null; reveal: boolean };
export type SquidRound = {
  number: number; total: number; amount: number; started_hand: number; at: number;
  members: { pid: string; name: string; count: number }[];
};
export type SquidSettlement = SquidRound & {
  id: string; status: 'settled' | 'cancelled'; reason?: string; finished_hand: number; finished_at: number;
  results: { pid: string; name: string; count: number; before: number; after: number; delta: number }[];
  payments: { pid: string; name: string; due: number; amount: number;
    transfers: { pid: string; name: string; due: number; amount: number }[] }[];
};
export type SquidEvent = {
  award: { id: string; pid: string; name: string; count: number; round: number; total: number; issued: number; at: number };
  settlement: SquidSettlement | null;
};
export type Player = {
  id: string;
  name: string;
  seat: number | null;
  stack: number;
  holding: number;
  buyin: number;
  buyout: number;
  profit: number;
  away: boolean;
  online: boolean;
  offline: number;
  bank: number;
  hands: number;
  achievements: { wins: number; busts: number };
  squid_count?: number | null;
  squid_held?: boolean;
  leave: boolean;
  banned: boolean;
  bet: number;
  folded: boolean;
  cards: (string | null)[];
};
export type JoinRequest = {
  id: string;
  kind: string;
  pid: string;
  name: string;
  seat: number;
  amount: number;
  approved: boolean;
};
export type Hand = {
  short_deck?: boolean;
  number: number;
  ids: string[];
  seats: number[];
  button: number;
  boards: string[][];
  deal?: { seq: number; start: number; until: number; previous: number[] } | null;
  active_board?: number;
  runout_result?: PotResult[];
  runout_equity?: {
    board: number;
    frames: Record<string, { total: number; wins: Record<string, number> }>;
  } | null;
  presentation?: SettlementPresentation | null;
  reveal_start?: number;
  own_hand_labels?: string[][];
  public_hand_labels?: Record<string, string[]>;
  showdown_results?: PotResult[];
  pots?: { amount: number; eligible: string[] }[];
  uncontested_winner?: string | null;
  bounty_rule?: BountyRule;
  bounty?: BountyAward | null;
  squid_rule?: SquidRule;
  squid?: SquidEvent | null;
  cards: Record<string, (string | null)[]>;
  revealed: string[];
  shown_cards: Record<string, number[]>;
  reveal_until: number;
  result: { pid: string; name: string; delta: number; won: number }[] | null;
  awards: { amounts: number[]; pot: number; board: number | null; winners?: number[] }[];
  votes: Record<string, boolean>;
  voters: string[];
  runouts: number | null;
  seq: number;
  clock: {
    pid: string;
    base_until: number;
    until: number;
    initial: number;
  } | null;
  last_actions: Record<string, string>;
};
export type ChipTransfer = {
  kind: 'pot' | 'bounty' | 'squid'; source: string | null; target: string;
  amount: number; start: number; until: number;
};
export type SettlementPresentation = {
  start: number; split_at: number; pot_until: number; until: number;
  bounty_at: number; squid_at: number;
  accounts: Record<string, { pid: string; name: string; seat: number | null; before: number }>;
  events: ChipTransfer[];
};
export type PotResult = {
  board: number;
  pot: number;
  winners: { pid: string; amount: number; label: string; cards: string[] }[];
};
export type Ledger = {
  id: string;
  pid: string;
  name: string;
  kind: string;
  amount: number;
  at: number;
  by: string;
  reverses: string | null;
};
export type Room = {
  short_deck_current?: boolean;
  id: string;
  name: string;
  settings: Config;
  bounty_current?: BountyRule;
  squid_current?: SquidRule;
  squid_round?: SquidRound | null;
  squid_history?: SquidSettlement[];
  owner: string;
  phase: string;
  deadline: number | null;
  button: number | null;
  small_blind: number | null;
  big_blind: number | null;
  number: number;
  started: boolean;
  paused: boolean;
  recovery: boolean;
  closing: boolean;
  closed_at: number | null;
  version: number;
  me: string;
  players: Player[];
  achievement_since: { wins: number; busts: number };
  achievement_pending?: { wins: number; busts: number };
  hand: Hand | null;
  server_time: number;
  requests: JoinRequest[];
  logs: { id: number; at: number; hand: number; kind: string; text: string }[];
  ledger: Ledger[];
  history: Hand[];
  rebuy: string[];
  straddle: string | null;
  pot: number;
  pots: number[];
  recovery_code: string;
  legal: {
    fold: boolean;
    call: number;
    can_call: boolean;
    can_raise: boolean;
    min_raise: number | null;
    max_raise: number | null;
  } | null;
};
